---
title: "Internal R in Pharma Seminar"
description: |
  Are you looking to host an internal R in Pharma event?
---

R in Pharma runs one of the largest Open Source pharma gatherings and training events in the world. Are you looking to host similar events within your organization?

### Hosting an internal R in Pharma Seminar

R in Pharma helps support various internal R events from Training Days, to R Hackathons to Internal Conferences.  Are you looking to better engage and unite your open source developers?

R in Pharma is committed to our users community and we are happy to help advise on how to enhance or start your own internally at your organization. 

Our team can help collaborate with your event efforts to help bring relevant content and information. We can help develop more tailored training and experiences for your Open Source audience.

### Looking to start a Open Source Competency Center vs Center of Excellence

Have you started an Open Source Competency Center and planning events? Feel free to reach out to R in Pharma for help about speakers, meetups & developing your site and tech.

### Community Adoption

We look forward to continuing our partnership with the user community to build relevant session content for our Open Source audience at our main fall gathering. Please feel free to reach out on how we can help with your internal event as well:

https://rinpharma.com/contact/

info @ rinpharma .com





